use_cuda: true
data_parallel: true
num_epochs: 600
output_dir: experiments/custom

model:
  name: efficientnet_b0
 # num_classes: 2
  num_classes: 100

dataset:
  name: custom_dataloaders
  root: data
 # batch_size: 32
 # image_size: 224
  batch_size: 32
  image_size: 448
  num_workers: 23

optimizer:
  name: SGD
  lr: 0.0125
  weight_decay: 1.e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: MultiStepLR
  milestones: [30, 60, 80]
  gamma: 0.1
